### ISSUE TITLE
Focus jumping.

### ISSUE THREAD

**Issue by nathanhammond** [ember-a11y/ember-a11y#2]
Navigating between routes reads correctly until Safari loses focus. Upon returning to Safari the focus jumps around when clicking a link.

### Reproduction
1. [Load the demo.](http://ember-a11y.github.io/ember-a11y/)
2. Click any of the links other than home.
3. Command-Tab away and right back.
4. Click any of the links other than the one you are presently on.

[Video demo.](https://www.dropbox.com/s/p28kmt3ar54wtco/Focus%20Jumping.mov?dl=0) Watch closely at ~37s.

### Actual
After Command-Tabbing away and back Safari loses track of how its focus is set. The focus jumps around to where it believes the cursor is.

### Expected
The focus should continue to be set correctly.

[Radar](https://openradar.appspot.com/radar?id=4983888472440832)

**Comment by nathanhammond** [comment]
@sarbbottam's [https://github.com/sarbbottam/spa-fm](research into focus jumping.)

**Comment by sarbbottam** [comment]
So far, the issue is only reproducible when there is `hash fragment identifier` in the url.
**VoiceOver/Safari in OS X El Capitan, is being clever, and trying to focus when there is a** `hash fragment identifier` **in the url.**

In the current implementation of [this repo](https://github.com/ember-a11y/ember-a11y/), it is not reproducible, as it is not using `hash fragment identifier`.

At [sarbbottam/spa-fm](https://github.com/sarbbottam/spa-fm), there are **four** implementations.

### Implementation

- [on-hash-change](https://github.com/sarbbottam/spa-fm/tree/master/lib/vanilla/on-hash-change) - router looks for change in `window.location.hash` and updates the view
- [on-click-prevent-default](https://github.com/sarbbottam/spa-fm/tree/master/lib/vanilla/on-click-prevent-default) - router looks for `href` attribute in the clicked `link`, _prevents the default behavior_, and updates the view
- [on-click-prevent-default-change-hash](https://github.com/sarbbottam/spa-fm/tree/master/lib/vanilla/on-click-prevent-default-change-hash) - router looks for `href` attribute in the clicked `link`, _prevents the default behavior_, updates the view and `window.location.hash`
- [on-click-prevent-default-change-location](https://github.com/sarbbottam/spa-fm/tree/master/lib/vanilla/on-click-prevent-default-change-location) - router looks for `href` attribute in the clicked `link`, _prevents the default behavior_, updates the view and `window.history`

### Observation

- [on-hash-change](https://github.com/sarbbottam/spa-fm/tree/master/lib/vanilla/on-hash-change) - jumping focus behavior in Safari & VoiceOver combination in El Capitan
- [on-click-prevent-default](https://github.com/sarbbottam/spa-fm/tree/master/lib/vanilla/on-click-prevent-default) - **no jumping focus behavior in Safari & VoiceOver combination in El Capitan**
- [on-click-prevent-default-change-hash](https://github.com/sarbbottam/spa-fm/tree/master/lib/vanilla/on-click-prevent-default-change-hash) - jumping focus behavior in Safari & VoiceOver combination in El Capitan
- [on-click-prevent-default-change-location](https://github.com/sarbbottam/spa-fm/tree/master/lib/vanilla/on-click-prevent-default-change-location) - **no jumping focus behavior in Safari & VoiceOver combination in El Capitan**

**Comment by mfairchild365** [comment]
Could this be related to http://mfairchild365.github.io/aria-tabs-vo-bug/ which is also using a hash?

**Comment by sarbbottam** [comment]
@mfairchild365 most likely.

**Comment by nathanhammond** [comment]
We've identified the problem and, as a consequence, the workaround: do not use `location: 'hash'` for routing inside of Ember applications. For now, since the failure is intermittent, we'll continue to use hash-based addressing in the demo application when deployed to `gh-pages`.

I'll close this with a new PR adding documentation.
