### ISSUE TITLE
willTransition deprecated

### ISSUE THREAD

**Issue by jrjohnson** [ember-a11y/ember-a11y#73]
`willTransition` has been deprecated since Ember 3.6 and will be removed in 4.0.0.

https://www.emberjs.com/deprecations/v3.x/#toc_deprecate-router-events.

It is in use in an instance initializer [here](https://github.com/ember-a11y/ember-a11y/blob/adc032a4045fdf8128e488e2b4d0bd924574d1e1/addon/instance-initializers/ember-a11y.js#L11)

**Comment by nathanhammond** [comment]
Hey @jrjohnson! Thanks for the heads up. I'm quite aware of the impending router changes. The entire addon will need to be revisited in the 4.0 time frame to make sure that everything still works. However, until then, I'm not planning to address this or make any changes. (Which is why I'll be closing the issue.)

This addon prioritizes stability and compatibility over adopting the most-recent version of APIs instantly. A deprecated but widely-used and tested API is therefore preferable to adopting the newest APIs.

Have no fear, the addon will be updated to support the new APIs once the there are [test failures in the beta channel](https://travis-ci.org/ember-a11y/ember-a11y/builds/500551530).

If you'd like to explore the effort of converting the addon to use the new router APIs I'd happily review a PR!

**Comment by jrjohnson** [comment]
Makes total sense @nathanhammond, I'll silence that warning in our app.  Thanks.

**Comment by tansongyang** [comment]
@nathanhammond, can anything be done like what the folks at [`ember-router-scroll`](https://github.com/dollarshaveclub/ember-router-scroll/pull/183/files#diff-7562eb8eba3c3d86a671045f8c70107eR22) did? They export different things depending on the Ember version so that they can support both pre- and post-3.6.0 without errors or warnings. Is it that change more difficult than it looks?

We could silence the warnings, but I'd rather not in case it covers up all other instances of the same warning. (Is there a way to silence warnings only from certain addons that I'm not aware of?)

**Comment by nathanhammond** [comment]
@tansongyang I'm committed to the functionality of this addon: it supports all the way back to 1.10. It will support 4.0 when the time comes. For reasons of my time and stability of the addon I do not intend to change the behavior for how this functions during the remainder of the 3.X lifecycle. It's likely that I _never_ change the behavior for 3.X applications, and that using this addon with 3.6+ will always result in a deprecation warning. I do not consider that a bug.

Aside: if the deprecations workflow doesn't meet your needs, I'd try to address that upstream.

In the mean time, I'm still happy to review PRs that may be created in an attempt to change my mind. 😛

**Comment by tansongyang** [comment]
@nathanhammond OK. I'll think about getting a PR for this.

I felt I should point out one more thing I discovered. I got a deprecation warning from [this line as well](https://github.com/ember-a11y/ember-a11y/blob/2498d42ca0e1f4d462d35d16586bf643e3e62113/addon/utils/pivot-route-identifier.js#L17). Looks like [HandlerInfos will be removed in 3.9.0](https://deprecations.emberjs.com/v3.x/#toc_remove-handler-infos), _not_ 4.0.0.

**Comment by nathanhammond** [comment]
@tansonyang thanks for the pointer. That appears like just a naming change, I’ll have something for it once 3.9 hits beta.

**Comment by mehulkar** [comment]
> That appears like just a naming change, I’ll have something for it once 3.9 hits beta.

Can we re-open this issue now that 3.9 is out?
